# Spring Boot 애플리케이션 기본 설정
spring:
  # 애플리케이션 이름 설정
  application:
    name: Musinsa-service

  # JSP 뷰 설정
  mvc:
    view:
      prefix: /WEB-INF/views/  # JSP 파일이 위치한 디렉토리 경로
      suffix: .jsp             # JSP 파일 확장자

  # 데이터베이스 연결 설정 (H2 인메모리 DB - 개발용)
  datasource:
    url: jdbc:h2:mem:testdb           # H2 인메모리 데이터베이스 URL
    driver-class-name: org.h2.Driver  # H2 데이터베이스 드라이버
    username: sa                      # 데이터베이스 사용자명
    password:                         # 데이터베이스 비밀번호 (빈값)

  # H2 콘솔 설정
  h2:
    console:
      enabled: true  # H2 웹 콘솔 활성화 (브라우저에서 DB 확인 가능)
      # 접속 URL: http://localhost:8080/h2-console

  # JPA/Hibernate 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # H2 데이터베이스용 방언 설정
    hibernate:
      ddl-auto: create-drop  # 애플리케이션 시작 시 테이블 생성, 종료 시 삭제
    show-sql: true           # 실행되는 SQL 쿼리를 콘솔에 출력

# MyBatis 설정
mybatis:
  # Mapper XML 파일 위치 설정
  mapper-locations: classpath:com.avengers.musinsa/*.xml              # resources/mapper/ 폴더의 모든 XML 파일
  type-aliases-package: com.avengers.musinsa.test        # 타입 별칭을 위한 패키지 (MyBatis에서 클래스명만으로 타입 사용 가능)